export const QUESTIONS = [
    "QUAL PERSONAGEM FEZ TAL COISA?",
    "QUAIS O PAIS MAIS FRIO DO MUNDO NO INVERNO?",
    "EM QUE ANO ACONTECEU O ACONTECIDO?",
    "QUAL O NOME DO FENOMEDO NATURAL?",
    "QUAL O NOME DO POTE DO SCHMIDT?",
    "DO QUE É FEITA A VARINHA DE HARRY POTTER?"
] as const;

export type Question = (typeof QUESTIONS)[number];